ksmbd: Fix removal of type parameter from vfs_path_parent_lookup()
/tmp/next/build/fs/smb/server/vfs.c:1255:30: error: too many arguments to function call, expected 5, have 6
 1254 |         err = vfs_path_parent_lookup(filename, flags | LOOKUP_BENEATH,
      |               ~~~~~~~~~~~~~~~~~~~~~~
 1255 |                                      path, &last, &type, &share_conf->vfs_path);
      |                                                          ^~~~~~~~~~~~~~~~~~~~~
/tmp/next/build/include/linux/namei.h:63:5: note: 'vfs_path_parent_lookup' declared here
   63 | int vfs_path_parent_lookup(struct filename *filename, unsigned int flags,
      |     ^                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   64 |                            struct path *parent, struct qstr *last,
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   65 |                            const struct path *root);
      |                            ~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: Mark Brown <broonie@kernel.org>